name = "MTRconnect-Universal26"
author = "Kardosadam"
version = "2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "13a7d375ab12af8d34bdd1bf3783921e5b2642f82f66914fb49cf08570ff67c1"

[versions]
fabric = "0.19.2"
minecraft = "1.20.1"
