name = "MTRconnect-Universal26"
author = "Kardosadam"
version = "2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a8cfec3733c2c1ef84ea24acda723cd14c060da2f001d8e1097f8c6a72b4b68d"

[versions]
fabric = "0.19.2"
minecraft = "1.20.1"
