name = "MTRconnect-Universal26"
author = "Kardosadam"
version = "2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "88b0f1f62a572b0e9278d04e5336b7e1458b54ce1f5fbb7e060f78deea34e3ff"

[versions]
fabric = "0.19.2"
minecraft = "1.20.1"
